### ISSUE TITLE
Great project!

### ISSUE THREAD

**Issue by mxlgv** [roryrjb/rf#1]
I have been looking for a normal file finder without dependencies for so long. With your permission, I am porting it to KolibriOS

**Comment by roryrjb** [comment]
@turbocat2001 thanks! Yeah it's a simple implementation, but for a lot of my use cases it works better than `find(1)`, although it's not as flexible or featureful. I've neglected the project a bit lately, and there's some bugs I've encountered that I usually work around or just put up with. Anyway glad you like it, of course you have permission. If you fix any bugs or add anything then I'd appreciate patches upstream!
